# Generated by Django 4.2.25 on 2026-05-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Szkic"),
                            ("pending_payment", "Oczekuje platnosci"),
                            ("confirmed", "Potwierdzona"),
                            ("cancelled", "Anulowana"),
                            ("expired", "Wygasla"),
                            ("converted_to_rental", "Przeksztalcona w wynajem"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=255)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="fleet.car",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="bookings.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "rezerwacja",
                "verbose_name_plural": "rezerwacje",
                "ordering": ["-start_at"],
                "indexes": [
                    models.Index(
                        fields=["car", "start_at", "end_at"],
                        name="bookings_re_car_id_4f2886_idx",
                    ),
                    models.Index(
                        fields=["status", "start_at"],
                        name="bookings_re_status_124d2d_idx",
                    ),
                ],
            },
        ),
    ]
