# Generated by Django 4.2.25 on 2026-05-22 09:53

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_reservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("daily_rental", "Wynajem dzienny"),
                            ("weekend_surcharge", "Doplata weekendowa"),
                            ("holiday_surcharge", "Doplata swiateczna"),
                            ("season_surcharge", "Doplata sezonowa"),
                            ("discount", "Rabat"),
                            ("extra_service", "Usluga dodatkowa"),
                            ("manual", "Pozycja reczna"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Liczba dni lub jednostek.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "source_code",
                    models.CharField(
                        blank=True,
                        help_text="Kod zrodla (np. extra child_seat, regula weekend).",
                        max_length=64,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_lines",
                        to="bookings.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "pozycja ceny",
                "verbose_name_plural": "pozycje ceny",
                "ordering": ["reservation", "sort_order", "pk"],
            },
        ),
    ]
