# Generated by Django 6.0.5 on 2026-05-22 10:37

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_priceline"),
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="custom_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Uzywane gdy pricing_mode=custom.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="pricing.pricelist",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Automatyczny (cennik na date)"),
                    ("price_list", "Wybrany cennik"),
                    ("custom", "Kwota reczna"),
                ],
                default="auto",
                max_length=16,
            ),
        ),
    ]
