# Generated by Django 6.0.5 on 2026-05-22 12:00

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_reservation_custom_total_reservation_price_list_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Zaplanowany"),
                            ("active", "Aktywny"),
                            ("returned", "Zwrocony"),
                            ("closed", "Zamkniety"),
                            ("cancelled", "Anulowany"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("scheduled_start_at", models.DateTimeField()),
                ("scheduled_end_at", models.DateTimeField()),
                ("actual_start_at", models.DateTimeField(blank=True, null=True)),
                ("actual_end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot kaucji z kategorii auta w momencie konwersji.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=255)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rentals_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental",
                        to="bookings.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "wynajem",
                "verbose_name_plural": "wynajmy",
                "ordering": ["-scheduled_start_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_start_at"],
                        name="bookings_re_status_d880ac_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_end_at"],
                        name="bookings_re_status_2726db_idx",
                    ),
                ],
            },
        ),
    ]
