# Generated by Django 4.2.25 on 2026-05-22 09:53

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("currency", models.CharField(default="PLN", max_length=3)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Domyslny cennik przy braku dopasowania dat.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "cennik",
                "verbose_name_plural": "cenniki",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("weekend_surcharge", "Doplata weekendowa"),
                            ("holiday_surcharge", "Doplata swiateczna"),
                            ("season_surcharge", "Doplata sezonowa"),
                            ("long_rental_discount", "Rabat dlugoterminowy"),
                            ("manual_discount", "Rabat reczny (panel)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "amount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Procent od sumy bazowej"),
                            ("fixed", "Kwota stala (cala rezerwacja)"),
                            ("per_day", "Kwota za kazdy dzien"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Okres obowiazywania (sezon, swieta).",
                        null=True,
                    ),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "min_rental_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Min. liczba dni wynajmu (rabat dlugoterminowy).",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Nizszy numer = wczesniejsza kolejnosc naliczania.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="pricing.pricelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "regula cenowa",
                "verbose_name_plural": "reguly cenowe",
                "ordering": ["price_list", "priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExtraService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("per_rental", "Za caly wynajem"),
                            ("per_day", "Za dobe"),
                            ("per_unit", "Za jednostke (np. km)"),
                        ],
                        default="per_rental",
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_services",
                        to="pricing.pricelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "usluga dodatkowa",
                "verbose_name_plural": "uslugi dodatkowe",
                "ordering": ["price_list", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DailyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Kwota za dobe (PLN).",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_rates",
                        to="fleet.carcategory",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_rates",
                        to="pricing.pricelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "stawka dzienna",
                "verbose_name_plural": "stawki dzienne",
                "ordering": ["price_list", "category__sort_order", "category__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="extraservice",
            constraint=models.UniqueConstraint(
                fields=("price_list", "code"), name="pricing_unique_extra_code_per_list"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyrate",
            constraint=models.UniqueConstraint(
                fields=("price_list", "category"),
                name="pricing_unique_daily_rate_per_list_category",
            ),
        ),
    ]
