# Generated by Django 6.0.5 on 2026-05-22 14:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0005_rental"),
        ("fleet", "0002_carcategory_deposit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HandoverProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        help_text="Przebieg przy wydaniu (km)."
                    ),
                ),
                (
                    "fuel_level_percent",
                    models.PositiveSmallIntegerField(
                        help_text="Poziom paliwa 0–100%.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handovers_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rental",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handover_protocol",
                        to="bookings.rental",
                    ),
                ),
            ],
            options={
                "verbose_name": "protokol wydania",
                "verbose_name_plural": "protokoly wydania",
            },
        ),
        migrations.CreateModel(
            name="ReturnProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        help_text="Przebieg przy zwrocie (km)."
                    ),
                ),
                (
                    "fuel_level_percent",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "surcharge_notes",
                    models.TextField(
                        blank=True,
                        help_text="Uwagi do doplat (np. paliwo, przekroczony limit km) — MVP tekst.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handover",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_protocol",
                        to="operations.handoverprotocol",
                    ),
                ),
                (
                    "rental",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_protocol",
                        to="bookings.rental",
                    ),
                ),
            ],
            options={
                "verbose_name": "protokol zwrotu",
                "verbose_name_plural": "protokoly zwrotu",
            },
        ),
        migrations.CreateModel(
            name="ProtocolPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="operations/protocols/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=120)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="operations.handoverprotocol",
                    ),
                ),
                (
                    "return_protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="operations.returnprotocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "zdjecie protokolu",
                "verbose_name_plural": "zdjecia protokolu",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DamageSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Drobne"),
                            ("moderate", "Srednie"),
                            ("major", "Poważne"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_at_capture",
                    models.CharField(
                        choices=[
                            ("active", "Aktywne"),
                            ("repaired", "Naprawione"),
                            ("written_off", "Odpisane"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_new_at_protocol",
                    models.BooleanField(
                        default=False,
                        help_text="True gdy uszkodzenie zgloszone przy tym protokole.",
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_damage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol_snapshots",
                        to="fleet.damage",
                    ),
                ),
                (
                    "handover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_snapshots",
                        to="operations.handoverprotocol",
                    ),
                ),
                (
                    "return_protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_snapshots",
                        to="operations.returnprotocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "snapshot uszkodzenia",
                "verbose_name_plural": "snapshoty uszkodzen",
                "ordering": ["captured_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signer_name", models.CharField(max_length=120)),
                ("image", models.ImageField(upload_to="operations/signatures/%Y/%m/")),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handover",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature",
                        to="operations.handoverprotocol",
                    ),
                ),
                (
                    "return_protocol",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature",
                        to="operations.returnprotocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "podpis",
                "verbose_name_plural": "podpisy",
            },
        ),
    ]
