# Generated by Django 4.2.25 on 2026-07-18 13:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0003_equipment_tank_damage_coords"),
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagesnapshot",
            name="damage_type",
            field=models.CharField(
                choices=[
                    ("R", "Rysa"),
                    ("W", "Wgniecenie"),
                    ("O", "Odprysk"),
                    ("P", "Pekniecie"),
                    ("B", "Brak elementu"),
                    ("U", "Inne uszkodzenie"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="damagesnapshot",
            name="pos_x",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="damagesnapshot",
            name="pos_y",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="handoverprotocol",
            name="current_step",
            field=models.CharField(default="driver", max_length=32),
        ),
        migrations.AddField(
            model_name="handoverprotocol",
            name="fuel_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reserve", "Rezerwa"),
                    ("quarter", "1/4"),
                    ("half", "1/2"),
                    ("three_quarter", "3/4"),
                    ("full", "Pełny"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="handoverprotocol",
            name="inspection_notes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="handoverprotocol",
            name="interior_notes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="handoverprotocol",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Szkic"),
                    ("ready_for_signature", "Gotowy do podpisu"),
                    ("completed", "Zakonczony"),
                    ("closed_without_signature", "Zamkniety bez podpisu"),
                ],
                db_index=True,
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="protocolphoto",
            name="category",
            field=models.CharField(
                choices=[
                    ("odometer", "Licznik"),
                    ("fuel_gauge", "Wskaznik paliwa"),
                    ("front", "Przod"),
                    ("rear", "Tyl"),
                    ("left", "Lewy bok"),
                    ("right", "Prawy bok"),
                    ("interior_front", "Wnetrze przod"),
                    ("interior_rear", "Wnetrze tyl"),
                    ("trunk", "Bagaznik"),
                    ("detail", "Szczegol"),
                    ("other", "Inne"),
                ],
                default="other",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="returnprotocol",
            name="actual_return_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnprotocol",
            name="cleanliness",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="returnprotocol",
            name="closure_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="returnprotocol",
            name="current_step",
            field=models.CharField(default="odometer", max_length=32),
        ),
        migrations.AddField(
            model_name="returnprotocol",
            name="fuel_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reserve", "Rezerwa"),
                    ("quarter", "1/4"),
                    ("half", "1/2"),
                    ("three_quarter", "3/4"),
                    ("full", "Pełny"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="returnprotocol",
            name="organizational_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="returnprotocol",
            name="return_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="returnprotocol",
            name="signature_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("signed", "Podpisano"),
                    ("signed_with_notes", "Podpisano z uwagami"),
                    ("refused", "Odmowa podpisu"),
                    ("absent", "Klient nieobecny"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="returnprotocol",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Szkic"),
                    ("ready_for_signature", "Gotowy do podpisu"),
                    ("completed", "Zakonczony"),
                    ("closed_without_signature", "Zamkniety bez podpisu"),
                ],
                db_index=True,
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="signature",
            name="customer_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="signature",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("signed", "Podpisano"),
                    ("signed_with_notes", "Podpisano z uwagami"),
                    ("refused", "Odmowa podpisu"),
                    ("absent", "Klient nieobecny"),
                ],
                default="signed",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="handoverprotocol",
            name="fuel_level_percent",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Kompatybilnosc wsteczna / cache procentu.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="handoverprotocol",
            name="mileage",
            field=models.PositiveIntegerField(
                blank=True, help_text="Przebieg przy wydaniu (km).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="returnprotocol",
            name="fuel_level_percent",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="returnprotocol",
            name="mileage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="returnprotocol",
            name="surcharge_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="signature",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="operations/signatures/%Y/%m/"
            ),
        ),
        migrations.CreateModel(
            name="ProtocolSettlementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=160)),
                ("basis", models.CharField(blank=True, max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Do decyzji"),
                            ("approved", "Zatwierdzona"),
                            ("rejected", "Odrzucona"),
                            ("deferred", "Do pozniejszej wyceny"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("staff_note", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "return_protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_lines",
                        to="operations.returnprotocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "pozycja rozliczenia",
                "verbose_name_plural": "pozycje rozliczenia",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolEquipmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_snapshot", models.CharField(max_length=120)),
                ("quantity_expected", models.PositiveSmallIntegerField(default=1)),
                (
                    "quantity_actual",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Do potwierdzenia"),
                            ("handed", "Przekazano"),
                            ("missing", "Brak"),
                            ("returned", "Zwrocono"),
                            ("returned_damaged", "Zwrocono uszkodzone"),
                            ("not_returned", "Nie zwrocono"),
                            ("note", "Uwaga"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "equipment_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protocol_lines",
                        to="fleet.equipmentitem",
                    ),
                ),
                (
                    "handover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_lines",
                        to="operations.handoverprotocol",
                    ),
                ),
                (
                    "return_protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_lines",
                        to="operations.returnprotocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "linia wyposazenia protokolu",
                "verbose_name_plural": "linie wyposazenia protokolu",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_additional", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=80)),
                ("last_name", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("id_document_type", models.CharField(blank=True, max_length=40)),
                ("id_document_number", models.CharField(blank=True, max_length=60)),
                ("id_document_country", models.CharField(blank=True, max_length=60)),
                ("license_number", models.CharField(blank=True, max_length=60)),
                ("license_country", models.CharField(blank=True, max_length=60)),
                ("license_issued_at", models.DateField(blank=True, null=True)),
                ("license_expires_at", models.DateField(blank=True, null=True)),
                ("document_verified", models.BooleanField(default=False)),
                ("license_valid", models.BooleanField(default=False)),
                ("license_category_ok", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handover",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver",
                        to="operations.handoverprotocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "kierowca protokolu",
                "verbose_name_plural": "kierowcy protokolu",
            },
        ),
        migrations.CreateModel(
            name="ProtocolDamageMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "damage_type",
                    models.CharField(
                        choices=[
                            ("R", "Rysa"),
                            ("W", "Wgniecenie"),
                            ("O", "Odprysk"),
                            ("P", "Pekniecie"),
                            ("B", "Brak elementu"),
                            ("U", "Inne uszkodzenie"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("size_note", models.CharField(blank=True, max_length=80)),
                ("pos_x", models.DecimalField(decimal_places=2, max_digits=5)),
                ("pos_y", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_new", models.BooleanField(default=True)),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("active", "Aktywne"),
                            ("mistaken", "Dodane omylkowo"),
                            ("repaired", "Naprawione"),
                            ("obsolete", "Nieaktualne"),
                            ("needs_assessment", "Wymaga oceny"),
                            ("needs_quote", "Wymaga wyceny"),
                            ("reported_at_return", "Zgloszone przy zwrocie"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_markers",
                        to="operations.handoverprotocol",
                    ),
                ),
                (
                    "return_protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_markers",
                        to="operations.returnprotocol",
                    ),
                ),
                (
                    "source_damage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol_markers",
                        to="fleet.damage",
                    ),
                ),
            ],
            options={
                "verbose_name": "marker uszkodzenia",
                "verbose_name_plural": "markery uszkodzen",
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.AddField(
            model_name="protocolphoto",
            name="damage_marker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="operations.protocoldamagemarker",
            ),
        ),
    ]
