# Generated by Django 6.0.5 on 2026-07-14 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0005_rental"),
        ("payments", "0005_rental_charge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("reservation_confirmed", "Rezerwacja potwierdzona"),
                            ("reservation_cancelled", "Rezerwacja anulowana"),
                            ("rental_created", "Wynajem utworzony"),
                            ("rental_started", "Wynajem rozpoczety"),
                            ("rental_returned", "Wynajem zwrocony"),
                            ("rental_closed", "Wynajem zamkniety"),
                            ("rental_cancelled", "Wynajem anulowany"),
                            ("payment_recorded", "Platnosc zarejestrowana"),
                            ("handover_completed", "Protokol wydania zakonczony"),
                            ("return_completed", "Protokol zwrotu zakonczony"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=32)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="payments.payment",
                    ),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="bookings.rental",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="bookings.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "wpis audytu",
                "verbose_name_plural": "wpisy audytu",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rental", "-created_at"],
                        name="audit_audit_rental__0133f1_idx",
                    ),
                    models.Index(
                        fields=["reservation", "-created_at"],
                        name="audit_audit_reserva_8fd3d0_idx",
                    ),
                ],
            },
        ),
    ]
