# Generated by Django 6.0.5 on 2026-05-20 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("make", models.CharField(max_length=80)),
                ("model", models.CharField(max_length=80)),
                ("year", models.PositiveSmallIntegerField()),
                ("vin", models.CharField(blank=True, max_length=17)),
                ("color", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktywny"),
                            ("inactive", "Nieaktywny"),
                            ("retired", "Wycofany"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Benzyna"),
                            ("diesel", "Diesel"),
                            ("electric", "Elektryczny"),
                            ("hybrid", "Hybryda"),
                            ("lpg", "LPG"),
                        ],
                        default="petrol",
                        max_length=20,
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(default=0, help_text="Przebieg w km"),
                ),
                ("seats", models.PositiveSmallIntegerField(default=5)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pojazd",
                "verbose_name_plural": "pojazdy",
                "ordering": ["make", "model", "registration_number"],
            },
        ),
        migrations.CreateModel(
            name="CarCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "kategoria pojazdu",
                "verbose_name_plural": "kategorie pojazdow",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("service", "Serwis"),
                            ("manual", "Reczna blokada"),
                            ("other", "Inna"),
                        ],
                        default="service",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="availability_blocks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_blocks",
                        to="fleet.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "blokada dostepnosci",
                "verbose_name_plural": "blokady dostepnosci",
                "ordering": ["-start_at"],
            },
        ),
        migrations.AddField(
            model_name="car",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars",
                to="fleet.carcategory",
            ),
        ),
        migrations.CreateModel(
            name="CarDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("insurance", "Ubezpieczenie OC/AC"),
                            ("inspection", "Przeglad techniczny"),
                            ("registration", "Dowod rejestracyjny"),
                            ("other", "Inny"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="fleet/documents/%Y/%m/")),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="fleet.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "dokument pojazdu",
                "verbose_name_plural": "dokumenty pojazdow",
                "ordering": ["-valid_until", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="fleet/cars/%Y/%m/")),
                ("is_primary", models.BooleanField(default=False)),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="fleet.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "zdjecie pojazdu",
                "verbose_name_plural": "zdjecia pojazdow",
                "ordering": ["-is_primary", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Damage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Np. zderzak przedni, drzwi lewe przednie",
                        max_length=120,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Drobne"),
                            ("moderate", "Srednie"),
                            ("major", "Poważne"),
                        ],
                        default="minor",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktywne"),
                            ("repaired", "Naprawione"),
                            ("written_off", "Odpisane"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("repaired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damages",
                        to="fleet.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "uszkodzenie",
                "verbose_name_plural": "uszkodzenia",
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="DamagePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="fleet/damages/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "damage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="fleet.damage",
                    ),
                ),
            ],
            options={
                "verbose_name": "zdjecie uszkodzenia",
                "verbose_name_plural": "zdjecia uszkodzen",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RepairRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("performed_at", models.DateField()),
                (
                    "mileage_at_service",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repairs",
                        to="fleet.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "wpis serwisowy",
                "verbose_name_plural": "wpisy serwisowe",
                "ordering": ["-performed_at"],
            },
        ),
    ]
