# Generated by Django 6.0.5 on 2026-05-22 10:37

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carcategory",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Kaucja zwrotna dla pojazdow tej kategorii (PLN).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
