# Generated by Django 4.2.25 on 2026-07-18 13:55

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def _backfill_tank_capacity(apps, schema_editor):
    Car = apps.get_model("fleet", "Car")
    Car.objects.filter(
        fuel_tank_capacity_liters__isnull=True,
    ).exclude(fuel_type="electric").update(
        fuel_tank_capacity_liters=Decimal("45.0"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0002_carcategory_deposit"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "pozycja wyposazenia",
                "verbose_name_plural": "katalog wyposazenia",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="car",
            name="fuel_tank_capacity_liters",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Pojemnosc baku w litrach (null dla EV bez baku).",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
            ),
        ),
        migrations.RunPython(_backfill_tank_capacity, migrations.RunPython.noop),
        migrations.AddField(
            model_name="damage",
            name="damage_type",
            field=models.CharField(
                choices=[
                    ("R", "Rysa"),
                    ("W", "Wgniecenie"),
                    ("O", "Odprysk"),
                    ("P", "Pekniecie"),
                    ("B", "Brak elementu"),
                    ("U", "Inne uszkodzenie"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="damage",
            name="pos_x",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Pozycja X na diagramie (0–100%).",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="damage",
            name="pos_y",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Pozycja Y na diagramie (0–100%).",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="damage",
            name="resolution_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mistaken", "Dodane omyłkowo"),
                    ("repaired", "Naprawione"),
                    ("obsolete", "Nieaktualne"),
                ],
                default="",
                help_text="Soft-close: omyłka / naprawione / nieaktualne.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CarEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_lines",
                        to="fleet.car",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="car_assignments",
                        to="fleet.equipmentitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "wyposazenie pojazdu",
                "verbose_name_plural": "wyposazenie pojazdow",
                "ordering": ["item__sort_order", "item__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="carequipment",
            constraint=models.UniqueConstraint(
                fields=("car", "item"), name="fleet_unique_car_equipment_item"
            ),
        ),
    ]
