# Generated by Django 6.0.5 on 2026-05-23 15:59

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.documents.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0005_rental"),
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("handover_protocol_pdf", "PDF protokolu wydania"),
                            ("return_protocol_pdf", "PDF protokolu zwrotu"),
                            ("invoice_pdf", "PDF faktury"),
                            ("rental_contract_pdf", "PDF umowy wynajmu"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "template_path",
                    models.CharField(
                        help_text="Sciezka szablonu Django, np. documents/pdf/handover_protocol.html",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "szablon dokumentu",
                "verbose_name_plural": "szablony dokumentow",
                "ordering": ["document_type", "slug"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("handover_protocol_pdf", "PDF protokolu wydania"),
                            ("return_protocol_pdf", "PDF protokolu zwrotu"),
                            ("invoice_pdf", "PDF faktury"),
                            ("rental_contract_pdf", "PDF umowy wynajmu"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.documents.models.document_upload_path
                    ),
                ),
                (
                    "content_type",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, help_text="SHA-256 hex skrotu pliku.", max_length=64
                    ),
                ),
                ("file_size_bytes", models.PositiveIntegerField(default=0)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="bookings.customer",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handover_protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="operations.handoverprotocol",
                    ),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="bookings.rental",
                    ),
                ),
                (
                    "return_protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="operations.returnprotocol",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.documenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "dokument",
                "verbose_name_plural": "dokumenty",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("sent", "Wyslany"),
                            ("failed", "Blad"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_logs",
                        to="documents.document",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "log email",
                "verbose_name_plural": "logi email",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=32, unique=True)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Szkic"),
                            ("issued", "Wystawiona"),
                            ("paid", "Oplacona"),
                            ("cancelled", "Anulowana"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="PLN", max_length=3)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="bookings.customer",
                    ),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="bookings.rental",
                    ),
                ),
            ],
            options={
                "verbose_name": "faktura",
                "verbose_name_plural": "faktury",
                "ordering": ["-issue_date", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_files",
                to="documents.invoice",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="documents.invoice",
                    ),
                ),
                (
                    "price_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_items",
                        to="bookings.priceline",
                    ),
                ),
            ],
            options={
                "verbose_name": "pozycja faktury",
                "verbose_name_plural": "pozycje faktury",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["rental", "document_type"],
                name="documents_d_rental__a47390_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type", "generated_at"],
                name="documents_d_documen_3fc4c0_idx",
            ),
        ),
    ]
