# Generated by Django 6.0.5 on 2026-05-24 08:11

from django.db import migrations, models

import apps.documents.models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage="private_documents",
                upload_to=apps.documents.models.document_upload_path,
            ),
        ),
    ]
