# Generated by Django 6.0.5 on 2026-05-24 08:12

from django.db import migrations, models

import apps.documents.models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_alter_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage=apps.documents.models.private_document_storage,
                upload_to=apps.documents.models.document_upload_path,
            ),
        ),
    ]
