# Generated by Django 6.0.5 on 2026-05-22 12:30

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0005_rental"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("rental_fee", "Oplata za wynajem"),
                            ("deposit", "Kaucja"),
                            ("refund", "Zwrot"),
                            ("extra_charge", "Oplata dodatkowa"),
                            ("damage_charge", "Oplata za szkody"),
                        ],
                        default="rental_fee",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("succeeded", "Zaksiegowana"),
                            ("failed", "Nieudana"),
                            ("cancelled", "Anulowana"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("external_reference", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="bookings.rental",
                    ),
                ),
            ],
            options={
                "verbose_name": "intencja platnosci",
                "verbose_name_plural": "intencje platnosci",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentProviderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_events",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "verbose_name": "zdarzenie bramki",
                "verbose_name_plural": "zdarzenia bramki",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("rental_fee", "Oplata za wynajem"),
                            ("deposit", "Kaucja"),
                            ("refund", "Zwrot"),
                            ("extra_charge", "Oplata dodatkowa"),
                            ("damage_charge", "Oplata za szkody"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Gotowka"),
                            ("bank_transfer", "Przelew"),
                            ("card", "Karta"),
                            ("blik", "BLIK"),
                            ("online_gateway", "Bramka online"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("paid_at", models.DateTimeField()),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="bookings.rental",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="bookings.reservation",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "verbose_name": "platnosc",
                "verbose_name_plural": "platnosci",
                "ordering": ["-paid_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["rental", "payment_type"],
                        name="payments_pa_rental__c1faf0_idx",
                    ),
                    models.Index(
                        fields=["paid_at"], name="payments_pa_paid_at_b40014_idx"
                    ),
                ],
            },
        ),
    ]
