# Generated by Django 4.2.25 on 2026-07-14 11:41

import django
import django.db.models.deletion
from django.db import migrations, models


def _paymentintent_target_constraint() -> models.CheckConstraint:
    q = models.Q(
        ("rental__isnull", False),
        ("reservation__isnull", False),
        _connector="OR",
    )
    kw = "condition" if django.VERSION >= (5, 1) else "check"
    return models.CheckConstraint(
        **{kw: q},
        name="paymentintent_requires_rental_or_reservation",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0005_rental"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintent",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_intents",
                to="bookings.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="rental",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_intents",
                to="bookings.rental",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=_paymentintent_target_constraint(),
        ),
    ]
