# Generated by Django 4.2.25 on 2026-07-14 16:40

from decimal import Decimal

import django
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def _rentalcharge_revenue_type_constraint() -> models.CheckConstraint:
    q = models.Q(payment_type="extra_charge") | models.Q(payment_type="damage_charge")
    kw = "condition" if django.VERSION >= (5, 1) else "check"
    return models.CheckConstraint(
        **{kw: q},
        name="rentalcharge_revenue_type_only",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0005_rental"),
        ("operations", "0001_initial"),
        ("payments", "0004_payment_rental_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("rental_fee", "Oplata za wynajem"),
                            ("deposit", "Kaucja"),
                            ("refund", "Zwrot"),
                            ("extra_charge", "Oplata dodatkowa"),
                            ("damage_charge", "Oplata za szkody"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_code", models.CharField(blank=True, max_length=32)),
                ("description", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="bookings.rental",
                    ),
                ),
                (
                    "return_protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="operations.returnprotocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "naliczenie wynajmu",
                "verbose_name_plural": "naliczenia wynajmu",
                "ordering": ["created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["rental", "payment_type"],
                        name="payments_re_rental__bc258d_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rentalcharge",
            constraint=_rentalcharge_revenue_type_constraint(),
        ),
    ]
